version: '3.8'

services: 
  mysqldb:
    image: mysql:8
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE = cine
      - MYSQL_USER = root
      - MYSQL_ROOT_PASSWORD=some_password
    ports: 
      - 3306:3306
    expose: 
      - '3306'
  app:
    depends_on:
      - mysqldb
    build: .
    restart: unless-stopped
    environment:
      - DB_HOST=mysqldb
    ports:
      - 4000:4000