DROP SCHEMA IF EXISTS TEST;

CREATE SCHEMA TEST;

USE TEST;

CREATE TABLE T(
	ID INT PRIMARY KEY AUTO_INCREMENT,
    VALOR INT
);

INSERT INTO T VALUES (NULL, 2);
INSERT INTO T VALUES (NULL, 6);
INSERT INTO T VALUES (NULL, 3);